version: 2
jobs:
  build:
    steps:
    - checkout  
    - restore_cache:
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum  "build.gradle" }}
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results
