version: 2
jobs:
  build:
    docker:
    - image: circleci/android:api-22
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout  
    - restore_cache:
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum  "build.gradle" }}
    - run:
        name: Run Tests
        command: ./gradlew lint test
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results
